---
# tasks file for systatroles
- name: disk info space for smoke cluster 
  shell: df -kh {{item}}
  register: df_ouput
  with_items: "{{  mountpoints | selectattr('name', 'equalto', 'smoke_cluster') | map(attribute='mountpoint') | list }}" 

- debug:
    var: df_ouput.results[0].stdout_lines
